import Head from "next/head";

const Custom404 = () => {
  return (
    <>
      <Head>
        <meta
          name="description"
          content="I'm a Front-end Developer / UI designer proficient in the use of Webflow, HTML, CSS, Tailwind CSS, JavaScript, React.js, Next.js Redux, Git and am skilled in the use of Figma and Photoshop."
        />

        <meta property="og:title" content="Ifeanyi Umeh" />

        <meta
          property="og:description"
          content="I'm a Front-end Developer / UI designer proficient in the use of Webflow, HTML, CSS, Tailwind CSS, JavaScript, React.js, Next.js Redux, Git and am skilled in the use of Figma and Photoshop."
        />

        <meta property="og:type" content="website" />

        <meta
          property="og:image"
          content="https://ifeanyiumeh.com/src/Profile_pix.png"
        />

        <meta property="og:url" content="https://ifeanyiumeh.com" />
        <title>404 | Ifeanyi Umeh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Favicon-sm.svg" />
        <link rel="apple-touch-icon" href="/Favicon-md.svg" />
      </Head>

      <div className="flex flex-col justify-center items-center h-screen px-[20px]">
        <div className="font-extrabold xs:text-[40px] sm:text-[60px] md:text-[70px] text-center">
          Oops!
        </div>
        <div className="xs:text-[16px] sm:text-[20px] md:text-[30px] text-center mb-[20px]">
          Page not found
        </div>
        <img src="/404.svg" alt="" className="max-h-[300px]" />
        <a
          href="/"
          className="cursor-pointer underline font-semibold text-red-600 xs:text-[14px] sm:text-[14px] md:text-[20px] text-center mt-[50px]"
        >
          Go to Home Page
        </a>
      </div>
    </>
  );
};

export default Custom404;
