export const products = [
  // NEW ARRIVALS

  // Gas cooker rpg-6631cc
  {
    slug: "rpg6631cc",
    cat: " Royal Gas Cooker",
    id: "1",
    title: "Royal 4-Burner Gas Cooker",
    desc: "RPG6631CC",
    img: "/4.png",
    img2: "/4a.png",
    img3: "/4b.png",
    img4: "/4c.png",
    feat1: "Royal 4-Burner Gas Cooker + Hot Plate",
    feat2: "Euro Pool Burners, Free Standing Oven",
    feat3: "Push Button Ignition for Hobs",
    feat4: "Adjustable Legs, Two Button Control",
    feat5: "Outside condenser, Gas Oven",
    featdesc: `Take your cooking to elevated levels today with Royal Gas Cookers. The RPG6631CC model comes with a free-standing oven that has been manufactured to give you an edge when it comes to whipping up tasty meals. It features 3 Euro pool gas burners with 1 hot plate, a tray, and a grill located within the oven. The cooker also comes with a glass top lid and a 2-button control. There’s also a wire shelf, gold ristiq button and handle while the cooker’s legs can be completely adjusted to your taste as well.
  `,
    link1: "/products/gas-cooker",
  },
  // AC elpicasso
  {
    slug: "el-picasso",
    cat: "Royal AC",
    id: "2",
    title: "Royal El Picasso",
    desc: "FLOOR STANDING",
    img: "/14.png",
    img2: "/14a.png",
    img3: "/14b.png",
    img4: "/14c.png",
    feat1: "Digital Inverter",
    feat2: "WiFi Function",
    feat3: "Wider. Farther. Faster Cooling",
    feat4: "Button Panel Display",
    feat5: "Fast Sleep Mode",
    featdesc: `Royal Picasso AC also features an efficient Digital Inverter Technology that ensures you get optimum cooling while consuming up to 70% less energy. This means you get to save more on your electricity bills while the durable air conditioner continues to operate effectively.

    Its WIFI function allows you to communicate with the AC using your smartphone as a remote controller. This can be done by downloading a dedicated mobile application for the cooling system. This way you get to adjust and control your Royal Picasso Air Conditioner without necessarily having to make use of regular remote controllers.
    
    Other impressive features of this AC include an auto-restart function, smart sleep mode, timer, turbo, extra long-distance air supply, super quiet operation, low voltage start-up, R410a gas, four-way swings, copper condenser, and I-clean functions.
    `,
    link1: "/products/air-conditioners",
  },
  // Microwave rmw20bhp
  {
    slug: "rmw20bhp",
    cat: "Royal Microwave Oven",
    id: "3",
    title: "Royal Microwave Oven",
    desc: "RMW20BHP",
    img: "/6.png",
    img2: "/6a.png",
    img3: null,
    img4: null,
    feat1: "20L Royal Microwave Oven",
    feat2: "6-Microwave power level",
    feat3: "Speed cooking",
    feat4: "Black Colour",
    feat5: "Automatic",
    featdesc: `Turn up the heat and whip up tasty confectioneries while using Royal Microwave Oven. This classy microwave oven works efficiently to cook your meals in the shortest time possible. Royal has created one of the best microwave ovens that you’ll find a crucial addition to your kitchen equipment. It has been built to operate manually with its 6-microwave power level for you to control the speed of your cooking to your satisfaction.
    `,
    link1: "/products/microwave",
  },
  // Boom box rhpas-b160
  {
    slug: "rhpas-b160",
    cat: "Royal Boom Box",
    id: "4",
    title: "Royal Boom Box",
    desc: "RHPAS-B160",
    img: "/8.png",
    img2: "/8a.png",
    img3: "/8b.png",
    img4: "/8c.png",
    feat1: "Royal 250-Litre Silver Chest Freezer",
    feat2: "High quality & efficient compressor",
    feat3: "Universal castor for easy moving",
    feat4: "Safety lock",
    feat5: "Outside condenser",
    featdesc: `Open up to real, freezing goodness that would keep the arctic blue with envy with Royal Chest Freezers. This 350-litre frosty box delivers epic speedy freezing thanks to its supreme quality and efficient compressor. Royal freezers are the best when it comes to total cooling and freezing. It also features an outside condenser, key & lock, and universal castor to ease its mobility.
    `,
    link1: "/products/sound-system",
  },
  // refrigerator rr-y380
  {
    slug: "rr-y380",
    slug2: "refrigerator",
    cat: "Royal Refrigerator",
    id: "5",
    title: "Royal Refrigerator",
    desc: "RR-Y380",
    img: "/1.png",
    img2: "/1a.png",
    img3: "/1b.png",
    img4: "/1c.png",
    lref: "/product/rr-y380",
    feat1: "Royal 250-Litre Silver Chest Freezer",
    feat2: "High quality & efficient compressor",
    feat3: "Universal castor for easy moving",
    feat4: "Safety lock",
    feat5: "Outside condenser",
    featdesc: `Open up to real, freezing goodness that would keep the arctic blue with envy with Royal Chest Freezers. This 350-litre frosty box delivers epic speedy freezing thanks to its supreme quality and efficient compressor. Royal freezers are the best when it comes to total cooling and freezing. It also features an outside condenser, key & lock, and universal castor to ease its mobility.
    `,
    link1: "/products/refrigerator",
  },
  // Washing machine rmwtt75hw
  {
    slug: "rmwtt75hw",
    cat: " Royal Washing Machine",
    id: "6",
    title: "Royal Washing Machine",
    desc: "RWMTT75HW",
    img: "/3.png",
    img2: "/3a.png",
    img3: "/3b.png",
    img4: "/3c.png",
    feat1: "Royal Washing Machine 9.5 Kg",
    feat2: "Twin Tub, Acrylic Door",
    feat3: "Button Panel Display",
    feat4: "Wind Jet Dry, AC Motor, Auto Pulsator",
    feat5: "Energy Saving",
    featdesc: `Royal washing machine with twin tub is effective for laundering and drying larger quantities of fabric. The panel display has buttons labeled carefully for easy understanding when operating the appliance. The first tub washes the laundry items. The second tub, on the other hand, spins and dries them up using its wind jet dry function. The washing appliance also comes with an auto pulsator. It is also eco-friendly with its energy-saving features. Whether its filthy briefs or dirty blankets, Royal washing machines will make sure they come out bright and clean.
    `,
    link1: "/products/washing-machine",
  },
  // AC split fb12rsa
  {
    slug: "fb12rsa",
    cat: "Royal AC",
    id: "7",
    title: "Royal Split AC",
    desc: "FB12RSA",
    img: "/17.png",
    img2: "/17a.png",
    img3: "/17b.png",
    img4: "/17c.png",
    feat1: "Low Voltage Starter",
    feat2: "Copper Condenser",
    feat3: "Turbo Cooling",
    feat4: "D*H*W indoor – 910*360*280mm Outdoor-850*370*620mm",
    feat5: "Air Purification: Indoor temp Indicator",
    featdesc: `Exude cool brilliance with Royal Split Air Conditioner. This AC comes with a low voltage starter (LVS) to mitigate potentially damaging electrical and mechanical shocks on the system. Its good sleep mode helps increase room temperature periodically to ensure a sound sleep for you. You can never go wrong when you choose Royal Air Conditioners as the split AC’s fast cooling feature ensures it works tirelessly to rapidly lower the room temperature.
    `,
    link1: "/products/air-conditioners",
  },

  // BEST SELLERS

  // refrigerator rr-y380
  {
    slug: "rr-y380",
    slug2: "refrigerator",
    cat: "Royal Refrigerator",
    id: "8",
    title: "Royal Refrigerator",
    desc: "RR-Y380",
    img: "/1.png",
    img2: "/1a.png",
    img3: "/1b.png",
    img4: "/1c.png",
    lref: "/product/rr-y380",
    feat1: "Royal 250-Litre Silver Chest Freezer",
    feat2: "High quality & efficient compressor",
    feat3: "Universal castor for easy moving",
    feat4: "Safety lock",
    feat5: "Outside condenser",
    featdesc: `Open up to real, freezing goodness that would keep the arctic blue with envy with Royal Chest Freezers. This 350-litre frosty box delivers epic speedy freezing thanks to its supreme quality and efficient compressor. Royal freezers are the best when it comes to total cooling and freezing. It also features an outside condenser, key & lock, and universal castor to ease its mobility.
    `,
    link1: "/products/refrigerator",
  },
  // chestfreezer rcf-s350
  {
    slug: "rcf-s350",
    slug2: "chest-freezer",
    cat: " Royal Chest Freezer",
    id: "9",
    title: "Royal 350-L Chest Freezer",
    desc: "RCF-S350",
    lref: "/product/rcf-s350",
    img: "/2.png",
    img2: "/2a.png",
    img3: "/2b.png",
    img4: "/2c.png",
    feat1: "Royal 250-Litre Silver Chest Freezer",
    feat2: "High quality & efficient compressor",
    feat3: "Universal castor for easy moving",
    feat4: "Safety lock",
    feat5: "Outside condenser",
    featdesc: `Open up to real, freezing goodness that would keep the arctic blue with envy with Royal Chest Freezers. This 350-litre frosty box delivers epic speedy freezing thanks to its supreme quality and efficient compressor. Royal freezers are the best when it comes to total cooling and freezing. It also features an outside condenser, key & lock, and universal castor to ease its mobility.
    `,
    link1: "/products/freezer",
  },
  // Washing machine rmwtt75hw
  {
    slug: "rmwtt75hw",
    cat: " Royal Washing Machine",
    id: "10",
    title: "Royal Washing Machine",
    desc: "RWMTT75HW",
    img: "/3.png",
    img2: "/3a.png",
    img3: "/3b.png",
    img4: "/3c.png",
    feat1: "Royal Washing Machine 9.5 Kg",
    feat2: "Twin Tub, Acrylic Door",
    feat3: "Button Panel Display",
    feat4: "Wind Jet Dry, AC Motor, Auto Pulsator",
    feat5: "Energy Saving",
    featdesc: `Royal washing machine with twin tub is effective for laundering and drying larger quantities of fabric. The panel display has buttons labeled carefully for easy understanding when operating the appliance. The first tub washes the laundry items. The second tub, on the other hand, spins and dries them up using its wind jet dry function. The washing appliance also comes with an auto pulsator. It is also eco-friendly with its energy-saving features. Whether its filthy briefs or dirty blankets, Royal washing machines will make sure they come out bright and clean.
    `,
    link1: "/products/washing-machine",
  },
  // Gas cooker rpg-6631cc
  {
    slug: "rpg6631cc",
    cat: " Royal Gas Cooker",
    id: "11",
    title: "Royal 4-Burner Gas Cooker",
    desc: "RPG6631CC",
    img: "/4.png",
    img2: "/4a.png",
    img3: "/4b.png",
    img4: "/4c.png",
    feat1: "Royal 4-Burner Gas Cooker + Hot Plate",
    feat2: "Euro Pool Burners, Free Standing Oven",
    feat3: "Push Button Ignition for Hobs",
    feat4: "Adjustable Legs, Two Button Control",
    feat5: "Outside condenser, Gas Oven",
    featdesc: `Take your cooking to elevated levels today with Royal Gas Cookers. The RPG6631CC model comes with a free-standing oven that has been manufactured to give you an edge when it comes to whipping up tasty meals. It features 3 Euro pool gas burners with 1 hot plate, a tray, and a grill located within the oven. The cooker also comes with a glass top lid and a 2-button control. There’s also a wire shelf, gold ristiq button and handle while the cooker’s legs can be completely adjusted to your taste as well.
    `,
    link1: "/products/gas-cooker",
  },
  // Microwave rmw20bhp
  {
    slug: "rmw20bhp",
    cat: "Royal Microwave Oven",
    id: "12",
    title: "Royal Microwave Oven",
    desc: "RMW20BHP",
    img: "/6.png",
    img2: "/6a.png",
    img3: null,
    img4: null,
    feat1: "20L Royal Microwave Oven",
    feat2: "6-Microwave power level",
    feat3: "Speed cooking",
    feat4: "Black Colour",
    feat5: "Automatic",
    featdesc: `Turn up the heat and whip up tasty confectioneries while using Royal Microwave Oven. This classy microwave oven works efficiently to cook your meals in the shortest time possible. Royal has created one of the best microwave ovens that you’ll find a crucial addition to your kitchen equipment. It has been built to operate manually with its 6-microwave power level for you to control the speed of your cooking to your satisfaction.
    `,
    link1: "/products/microwave",
  },
  // TV rtv49sdk9
  {
    slug: "rtv49sdk9",
    cat: "Royal TV",
    id: "13",
    title: "Royal UHD Smart TV",
    desc: "RTV49SDK9",
    img: "/7.png",
    img2: "/7a.png",
    img3: "/7b.png",
    img4: "/7c.png",
    feat1: "Royal 49″ UHD Smart Soundbar TV",
    feat2: "Titanium Golden Finish",
    feat3: "1GB RAM/ 8GB MEMORY",
    feat4: "VGA",
    feat5: "2 HDMI, 2 USB",
    featdesc: `Be inspired by a whole new viewing experience with Royal 49″ UHD Smart Soundbar TV. Sports and movies will come out looking as real as the action. Music videos and documentaries will be experienced in a whole new light. Royal TV’s classic design is sure to make you fall in love with it. Its new soundbar support ensures that the audio from your TV sounds captivating and uniquely different from what you’re used to. Its system comes with 1GB RAM and 8GB memory. The TV also features 2 HDMI ports, 2 USB ports, and VGA.
    `,
    link1: "/products/television",
  },
  // Boom box rhpas-b160
  {
    slug: "rhpas-b160",
    cat: "Royal Boom Box",
    id: "14",
    title: "Royal Boom Box",
    desc: "RHPAS-B160",
    img: "/8.png",
    img2: "/8a.png",
    img3: "/8b.png",
    img4: "/8c.png",
    feat1: "Royal 250-Litre Silver Chest Freezer",
    feat2: "High quality & efficient compressor",
    feat3: "Universal castor for easy moving",
    feat4: "Safety lock",
    feat5: "Outside condenser",
    featdesc: `Open up to real, freezing goodness that would keep the arctic blue with envy with Royal Chest Freezers. This 350-litre frosty box delivers epic speedy freezing thanks to its supreme quality and efficient compressor. Royal freezers are the best when it comes to total cooling and freezing. It also features an outside condenser, key & lock, and universal castor to ease its mobility.
    `,
    link1: "/products/sound-system",
  },
  // AC elpicasso
  {
    slug: "el-picasso",
    cat: "Royal AC",
    id: "15",
    title: "Royal El Picasso",
    desc: "FLOOR STANDING",
    img: "/14.png",
    img2: "/14a.png",
    img3: "/14b.png",
    img4: "/14c.png",
    feat1: "Digital Inverter",
    feat2: "WiFi Function",
    feat3: "Wider. Farther. Faster Cooling",
    feat4: "Button Panel Display",
    feat5: "Fast Sleep Mode",
    featdesc: `Royal Picasso AC also features an efficient Digital Inverter Technology that ensures you get optimum cooling while consuming up to 70% less energy. This means you get to save more on your electricity bills while the durable air conditioner continues to operate effectively.

    Its WIFI function allows you to communicate with the AC using your smartphone as a remote controller. This can be done by downloading a dedicated mobile application for the cooling system. This way you get to adjust and control your Royal Picasso Air Conditioner without necessarily having to make use of regular remote controllers.
    
    Other impressive features of this AC include an auto-restart function, smart sleep mode, timer, turbo, extra long-distance air supply, super quiet operation, low voltage start-up, R410a gas, four-way swings, copper condenser, and I-clean functions.
    `,
    link1: "/products/air-conditioners",
  },
  // AC split fb12rsa
  {
    slug: "fb12rsa",
    cat: "Royal AC",
    id: "16",
    title: "Royal Split AC",
    desc: "FB12RSA",
    img: "/17.png",
    img2: "/17a.png",
    img3: "/17b.png",
    img4: "/17c.png",
    feat1: "Low Voltage Starter",
    feat2: "Copper Condenser",
    feat3: "Turbo Cooling",
    feat4: "D*H*W indoor – 910*360*280mm Outdoor-850*370*620mm",
    feat5: "Air Purification: Indoor temp Indicator",
    featdesc: `Exude cool brilliance with Royal Split Air Conditioner. This AC comes with a low voltage starter (LVS) to mitigate potentially damaging electrical and mechanical shocks on the system. Its good sleep mode helps increase room temperature periodically to ensure a sound sleep for you. You can never go wrong when you choose Royal Air Conditioners as the split AC’s fast cooling feature ensures it works tirelessly to rapidly lower the room temperature.
    `,
    link1: "/products/air-conditioners",
  },


  // Televisions

  // TV RTV40DN5
  {
    slug: "rtv40dn5",
    cat: "Royal TV",
    id: "17",
    title: "Royal 40″ FHD TV",
    desc: "RTV40DN5",
    img: "/10.png",
    img2: "/10a.png",
    img3: "/10b.png",
    img4: "/10c.png",
    feat1: "Slim Bezel, HD",
    feat2: "High brightness/high contrast",
    feat3: "HDMI & USB Movie",
    feat4: "1 Coaxial, 2 HDMI-IN, 1 VGA",
    feat5: "Energy saving",
    featdesc: `Enjoy crisp <br/> and clear picture quality with Royal 40″ FHD TV. This slim bezel TV comes with dynamic brightness and high contrast settings to give you a view unlike what you’ve ever seen before. Its energy-saving feature means you won’t be putting unnecessary pressure on your electricity bills. The TV comes with 2 HDMI ports, 1 VGA port, 1 coaxial, 1 PC audio-in, 1 Antenna-in, 2 AV-in, 2 USB ports, and an earphone-out. This classic TV is real value for money.
    `,
    link1: "/products/television",
  },
  // TV rtv49sdk9
  {
    slug: "rtv49sdk9",
    cat: "Royal TV",
    id: "18",
    title: "Royal UHD Smart TV",
    desc: "RTV49SDK9",
    img: "/7.png",
    img2: "/7a.png",
    img3: "/7b.png",
    img4: "/7c.png",
    feat1: "Royal 49″ UHD Smart Soundbar TV",
    feat2: "Titanium Golden Finish",
    feat3: "1GB RAM/ 8GB MEMORY",
    feat4: "VGA",
    feat5: "2 HDMI, 2 USB",
    featdesc: `Be inspired by a whole new viewing experience with Royal 49″ UHD Smart Soundbar TV. Sports and movies will come out looking as real as the action. Music videos and documentaries will be experienced in a whole new light. Royal TV’s classic design is sure to make you fall in love with it. Its new soundbar support ensures that the audio from your TV sounds captivating and uniquely different from what you’re used to. Its system comes with 1GB RAM and 8GB memory. The TV also features 2 HDMI ports, 2 USB ports, and VGA.
    `,
    link1: "/products/television",
  },
  // TV rtv49sdk9
  {
    slug: "rtv49sdk9",
    cat: "Royal TV",
    id: "19",
    title: "Royal UHD Smart TV",
    desc: "RTV49SDK9",
    img: "/7.png",
    img2: "/7a.png",
    img3: "/7b.png",
    img4: "/7c.png",
    feat1: "Royal 49″ UHD Smart Soundbar TV",
    feat2: "Titanium Golden Finish",
    feat3: "1GB RAM/ 8GB MEMORY",
    feat4: "VGA",
    feat5: "2 HDMI, 2 USB",
    featdesc: `Be inspired by a whole new viewing experience with Royal 49″ UHD Smart Soundbar TV. Sports and movies will come out looking as real as the action. Music videos and documentaries will be experienced in a whole new light. Royal TV’s classic design is sure to make you fall in love with it. Its new soundbar support ensures that the audio from your TV sounds captivating and uniquely different from what you’re used to. Its system comes with 1GB RAM and 8GB memory. The TV also features 2 HDMI ports, 2 USB ports, and VGA.
    `,
    link1: "/products/television",
  },
  // TV rtv49sdk9
  {
    slug: "rtv49sdk9",
    cat: "Royal TV",
    id: "20",
    title: "Royal UHD Smart TV",
    desc: "RTV49SDK9",
    img: "/7.png",
    img2: "/7a.png",
    img3: "/7b.png",
    img4: "/7c.png",
    feat1: "Royal 49″ UHD Smart Soundbar TV",
    feat2: "Titanium Golden Finish",
    feat3: "1GB RAM/ 8GB MEMORY",
    feat4: "VGA",
    feat5: "2 HDMI, 2 USB",
    featdesc: `Be inspired by a whole new viewing experience with Royal 49″ UHD Smart Soundbar TV. Sports and movies will come out looking as real as the action. Music videos and documentaries will be experienced in a whole new light. Royal TV’s classic design is sure to make you fall in love with it. Its new soundbar support ensures that the audio from your TV sounds captivating and uniquely different from what you’re used to. Its system comes with 1GB RAM and 8GB memory. The TV also features 2 HDMI ports, 2 USB ports, and VGA.
    `,
    link1: "/products/television",
  },
  // TV rtv49sdk9
  {
    slug: "rtv49sdk9",
    cat: "Royal TV",
    id: "21",
    title: "Royal UHD Smart TV",
    desc: "RTV49SDK9",
    img: "/7.png",
    img2: "/7a.png",
    img3: "/7b.png",
    img4: "/7c.png",
    feat1: "Royal 49″ UHD Smart Soundbar TV",
    feat2: "Titanium Golden Finish",
    feat3: "1GB RAM/ 8GB MEMORY",
    feat4: "VGA",
    feat5: "2 HDMI, 2 USB",
    featdesc: `Be inspired by a whole new viewing experience with Royal 49″ UHD Smart Soundbar TV. Sports and movies will come out looking as real as the action. Music videos and documentaries will be experienced in a whole new light. Royal TV’s classic design is sure to make you fall in love with it. Its new soundbar support ensures that the audio from your TV sounds captivating and uniquely different from what you’re used to. Its system comes with 1GB RAM and 8GB memory. The TV also features 2 HDMI ports, 2 USB ports, and VGA.
    `,
    link1: "/products/television",
  },
  // TV rtv49sdk9
  {
    slug: "rtv49sdk9",
    cat: "Royal TV",
    id: "22",
    title: "Royal UHD Smart TV",
    desc: "RTV49SDK9",
    img: "/7.png",
    img2: "/7a.png",
    img3: "/7b.png",
    img4: "/7c.png",
    feat1: "Royal 49″ UHD Smart Soundbar TV",
    feat2: "Titanium Golden Finish",
    feat3: "1GB RAM/ 8GB MEMORY",
    feat4: "VGA",
    feat5: "2 HDMI, 2 USB",
    featdesc: `Be inspired by a whole new viewing experience with Royal 49″ UHD Smart Soundbar TV. Sports and movies will come out looking as real as the action. Music videos and documentaries will be experienced in a whole new light. Royal TV’s classic design is sure to make you fall in love with it. Its new soundbar support ensures that the audio from your TV sounds captivating and uniquely different from what you’re used to. Its system comes with 1GB RAM and 8GB memory. The TV also features 2 HDMI ports, 2 USB ports, and VGA.
    `,
    link1: "/products/television",
  },
  // TV rtv49sdk9
  {
    slug: "rtv49sdk9",
    cat: "Royal TV",
    id: "22",
    title: "Royal UHD Smart TV",
    desc: "RTV49SDK9",
    img: "/7.png",
    img2: "/7a.png",
    img3: "/7b.png",
    img4: "/7c.png",
    feat1: "Royal 49″ UHD Smart Soundbar TV",
    feat2: "Titanium Golden Finish",
    feat3: "1GB RAM/ 8GB MEMORY",
    feat4: "VGA",
    feat5: "2 HDMI, 2 USB",
    featdesc: `Be inspired by a whole new viewing experience with Royal 49″ UHD Smart Soundbar TV. Sports and movies will come out looking as real as the action. Music videos and documentaries will be experienced in a whole new light. Royal TV’s classic design is sure to make you fall in love with it. Its new soundbar support ensures that the audio from your TV sounds captivating and uniquely different from what you’re used to. Its system comes with 1GB RAM and 8GB memory. The TV also features 2 HDMI ports, 2 USB ports, and VGA.
    `,
    link1: "/products/television",
  },
];

// export const fetchProjectID = (id) => {
//   const fetchedProject = portfolioProject.find(
//     (project) => project.slug === id
//   );
//   return fetchedProject;
// };
