import React from "react";
import Head from "next/head";
import { BiCommentDots } from "react-icons/bi";
import { blogs } from "../../blogsAPI";

const blog = ({ blogg }) => {
  return (
    <div>
      <Head>
        <meta
          name="description"
          content="Check out all the projects I have done."
        />

        <meta property="og:title" content="" />

        <meta
          property="og:description"
          content=""
        />

        <meta property="og:type" content="website" />

        <meta
          property="og:image"
          content=""
        />

        <meta property="og:url" content="" />
        <title>Royal Blog - {blogg.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-sm.svg" />
        <link rel="apple-touch-icon" href="/favicon-md.svg" />
      </Head>

      <div className="w-full select-none relative xs:mt-[100px] md:mt-[170px] xs:mb-[60px] md:mb-[120px]">
        <div className="max-w-[1240px] mx-auto flex flex-col items-center justify-center relative xs:px-[0px] md:px-[20px]">
          {/* Blog heading */}
          <div className="flex flex-col items-center justify-center mb-[30px]">
            <h1 className="font-bold xs:text-[30px] md:text-[40px] xs:text-center leading-[40px] xs:mb-[10px]">
              {blogg.title}
            </h1>
            <div className="flex items-center group mb-[20px]">
              <p className="mr-[10px] text-black/50 xs:text-[20px] md:text-[22px]">
                {blogg.date}
              </p>
              <div className="text-[26px] text-royal text-black/50">
                <BiCommentDots />
              </div>
            </div>
          </div>

          {/* Blog Image */}
          <div className="md-[30px]">
            <img src={blogg.img} alt={blogg.title} objectfit="cover" />
          </div>

          {/* Paragraph 1 */}
          <div className="flex flex-col mt-[30px] px-[20px]">
            {blogg.p1a1 && (
              <p className="font-bold xs:text-[20px] md:text-[24px] mb-[10px]">
                {blogg.p1a1}
              </p>
            )}
            {blogg.p1a2 && (
              <p className="xs:text-[14px] md:text-[18px] mb-[10px]">
                {blogg.p1a2}
              </p>
            )}
            {blogg.p1b1 && (
              <p className="font-bold xs:text-[18px] md:text-[22px] mb-[10px]">
                {blogg.p1b1}
              </p>
            )}
            <ul className="xs:text-[14px] md:text-[18px] mb-[10px] list-disc ml-[20px]">
              {blogg.p1b2 && <li className="">{blogg.p1b2}</li>}
              {blogg.p1b3 && <li className="">{blogg.p1b3}</li>}
              {blogg.p1b4 && <li className="">{blogg.p1b4}</li>}
              {blogg.p1b5 && <li className="">{blogg.p1b5}</li>}
              {blogg.p1b6 && <li className="">{blogg.p1b6}</li>}
              {blogg.p1b7 && <li className="">{blogg.p1b7}</li>}
              {blogg.p1b8 && <li className="">{blogg.p1b8}</li>}
            </ul>
          </div>


          {/* Paragraph 2 */}
          <div className="flex flex-col mt-[30px] px-[20px]">
            {blogg.p2a1 && (
              <p className="font-bold xs:text-[20px] md:text-[24px] mb-[10px]">
                {blogg.p2a1}
              </p>
            )}
            {blogg.p2a2 && (
              <p className="xs:text-[14px] md:text-[18px] mb-[10px]">
                {blogg.p2a2}
              </p>
            )}
            {blogg.p2b1 && (
              <p className="font-bold xs:text-[18px] md:text-[22px] mb-[10px]">
                {blogg.p2b1}
              </p>
            )}
            <ul className="xs:text-[14px] md:text-[18px] mb-[10px] list-disc ml-[20px]">
              {blogg.p2b2 && <li className="">{blogg.p2b2}</li>}
              {blogg.p2b3 && <li className="">{blogg.p2b3}</li>}
              {blogg.p2b4 && <li className="">{blogg.p2b4}</li>}
              {blogg.p2b5 && <li className="">{blogg.p2b5}</li>}
              {blogg.p2b6 && <li className="">{blogg.p2b6}</li>}
              {blogg.p2b7 && <li className="">{blogg.p2b7}</li>}
              {blogg.p2b8 && <li className="">{blogg.p2b8}</li>}
            </ul>
          </div>

          {/* Paragraph 3 */}
          <div className="flex flex-col mt-[30px] px-[20px]">
            {blogg.p3a1 && (
              <p className="font-bold xs:text-[20px] md:text-[24px] mb-[10px]">
                {blogg.p3a1}
              </p>
            )}
            {blogg.p3a2 && (
              <p className="xs:text-[14px] md:text-[18px] mb-[10px]">
                {blogg.p3a2}
              </p>
            )}
            {blogg.p3b1 && (
              <p className="font-bold xs:text-[18px] md:text-[22px] mb-[10px]">
                {blogg.p3b1}
              </p>
            )}
            <ul className="xs:text-[14px] md:text-[18px] mb-[10px] list-disc ml-[20px]">
              {blogg.p3b2 && <li className="">{blogg.p3b2}</li>}
              {blogg.p3b3 && <li className="">{blogg.p3b3}</li>}
              {blogg.p3b4 && <li className="">{blogg.p3b4}</li>}
              {blogg.p3b5 && <li className="">{blogg.p3b5}</li>}
              {blogg.p3b6 && <li className="">{blogg.p3b6}</li>}
              {blogg.p3b7 && <li className="">{blogg.p3b7}</li>}
              {blogg.p3b8 && <li className="">{blogg.p3b8}</li>}
            </ul>
          </div>

          {/* Paragraph 4 */}
          <div className="flex flex-col mt-[30px] px-[20px]">
            {blogg.p4a1 && (
              <p className="font-bold xs:text-[20px] md:text-[24px] mb-[10px]">
                {blogg.p4a1}
              </p>
            )}
            {blogg.p4a2 && (
              <p className="xs:text-[14px] md:text-[18px] mb-[10px]">
                {blogg.p4a2}
              </p>
            )}
            {blogg.p4b1 && (
              <p className="font-bold xs:text-[18px] md:text-[22px] mb-[10px]">
                {blogg.p4b1}
              </p>
            )}
            <ul className="xs:text-[14px] md:text-[18px] mb-[10px] list-disc ml-[20px]">
              {blogg.p4b2 && <li className="">{blogg.p4b2}</li>}
              {blogg.p4b3 && <li className="">{blogg.p4b3}</li>}
              {blogg.p4b4 && <li className="">{blogg.p4b4}</li>}
              {blogg.p4b5 && <li className="">{blogg.p4b5}</li>}
              {blogg.p4b6 && <li className="">{blogg.p4b6}</li>}
              {blogg.p4b7 && <li className="">{blogg.p4b7}</li>}
              {blogg.p4b8 && <li className="">{blogg.p4b8}</li>}
            </ul>
          </div>

          {/* Paragraph 5 */}
          <div className="flex flex-col mt-[30px] px-[20px]">
            {blogg.p5a1 && (
              <p className="font-bold xs:text-[20px] md:text-[24px] mb-[10px]">
                {blogg.p5a1}
              </p>
            )}
            {blogg.p5a2 && (
              <p className="xs:text-[14px] md:text-[18px] mb-[10px]">
                {blogg.p5a2}
              </p>
            )}
            {blogg.p5b1 && (
              <p className="font-bold xs:text-[18px] md:text-[22px] mb-[10px]">
                {blogg.p5b1}
              </p>
            )}
            <ul className="xs:text-[14px] md:text-[18px] mb-[10px] list-disc ml-[20px]">
              {blogg.p5b2 && <li className="">{blogg.p5b2}</li>}
              {blogg.p5b3 && <li className="">{blogg.p5b3}</li>}
              {blogg.p5b4 && <li className="">{blogg.p5b4}</li>}
              {blogg.p5b5 && <li className="">{blogg.p5b5}</li>}
              {blogg.p5b6 && <li className="">{blogg.p5b6}</li>}
              {blogg.p5b7 && <li className="">{blogg.p5b7}</li>}
              {blogg.p5b8 && <li className="">{blogg.p5b8}</li>}
            </ul>
          </div>


        </div>
      </div>
    </div>
  );
};

export default blog;

export const getStaticProps = async ({ params }) => {
  const data = blogs.filter((p) => p.slug === params.slug);

  return {
    props: {
      blogg: data[0],
    },
  };
};

export const getStaticPaths = async () => {
  const paths = blogs.map((blogg) => ({
    params: { slug: blogg.slug },
  }));
  return { paths, fallback: false };
};
