import React from "react";
import Head from "next/head";
import { BiCommentDots } from "react-icons/bi";
import { MdDateRange } from "react-icons/md";
import { blogs } from "../../blogsAPI";
import Link from "next/link";
import Loader from "../../components/Loader";
import { graphCMSImageLoader } from "../../util";
import { getBlogs, getBlogDetails } from "../../services";
import { useRouter } from "next/router";
import Image from "next/image";
import BlogMainSection from "../../components/ProductPage/BlogMainSection";
import Blog from "../../components/Blog";
import BlogSideSection from "../../components/ProductPage/BlogSideSection";
import LinkTree2 from "../../components/ProductPage/LinkTree2";

const blog = ({ blog }) => {
  return (
    <div>
      <Head>
        <meta
          name="description"
          content="Check out all the projects I have done."
        />

        <meta property="og:title" content="" />

        <meta property="og:description" content="" />

        <meta property="og:type" content="website" />

        <meta property="og:image" content="" />

        <meta property="og:url" content="" />
        <title>Royal Blog - {blog.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-sm.svg" />
        <link rel="apple-touch-icon" href="/favicon-md.svg" />
      </Head>

      <LinkTree2 title={blog.title} className=""/>
      <div className="w-full select-none relative xs:mt-[250px] md:mt-[200px] xs:mb-[60px] md:mb-[120px]">
        <div className="max-w-[1240px] mx-auto flex flex-col relative xs:px-[0px] md:px-[20px]">
          <BlogMainSection
            className=""
            title={blog.title}
            date={blog.date}
            image={blog.image.url}
            content={blog.content.raw.children}
          />
        </div>
      </div>
    </div>
  );
};

export default blog;

export async function getStaticProps({ params }) {
  const data = await getBlogDetails(params.slug);
  return {
    props: {
      blog: data,
    },
  };
}

export async function getStaticPaths() {
  const blogs = await getBlogs();

  return {
    paths: blogs.map(({ node: { slug } }) => ({ params: { slug } })),
    fallback: false,
  };
}

// export async function getStaticProps({ params }) {
//   const blogs = await getBlogs(params.slug);
//   return {
//     props: { blogs },
//   };
// }
