import React from "react";
import Head from "next/head";
import BlogPageSection from "../../components/ProductPage/BlogPageSection";

const blogs = () => {
  return (
    <div>
      <Head>
        <meta
          name="description"
          content="Check out all the projects I have done."
        />

        <meta property="og:title" content="Projects | Ifeanyi Umeh" />

        <meta
          property="og:description"
          content="Check out all the projects I have done."
        />

        <meta property="og:type" content="website" />

        <meta
          property="og:image"
          content="https://ifeanyiumeh.com/src/Profile_pix.png"
        />

        <meta property="og:url" content="https://ifeanyiumeh.com" />
        <title>Blog - Royal Electronics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-sm.svg" />
        <link rel="apple-touch-icon" href="/favicon-md.svg" />
      </Head>

        <BlogPageSection />

    </div>
  );
};

export default blogs;
