import React from "react";
import Head from "next/head";

const storelocator = () => {
  return (
    <div>
      <Head>
        <meta
          name="description"
          content="Check out all the projects I have done."
        />

        <meta property="og:title" content="" />

        <meta property="og:description" content="" />

        <meta property="og:type" content="website" />

        <meta property="og:image" content="" />

        <meta property="og:url" content="" />
        <title>Store locator - Royal Electronics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-sm.svg" />
        <link rel="apple-touch-icon" href="/favicon-md.svg" />
      </Head>

      <div className="w-full bg-white select-none relative xs:mt-[100px] md:mt-[170px] xs:mb-[60px] md:mb-[120px]">
        <div className="max-w-[1240px] mx-auto flex flex-col items-center justify-center relative xs:px-[0px] md:px-[20px]">
          <h1 className="font-bold xs:text-[30px] md:text-[40px] xs:text-center leading-[40px] xs:mb-[10px] px-[20px] mb-[0px]">
            Royal Store Locator
          </h1>

          <div className="w-full mt-[50px]">
            <iframe
              src="https://my.atlistmaps.com/map/30c7da61-8c3c-40b2-8026-70df29e3ecb2?share=true"
              allow="geolocation"
              width="100%"
              height="800px"
              frameborder="0"
              scrolling="no"
              allowfullscreen
            ></iframe>
          </div>
        </div>
      </div>
    </div>
  );
};

export default storelocator;
