import React from "react";
import Partners from "../../components/Partners";
import Head from "next/head";

const StoreLocator = () => {
  return (
    <div className="">
      <Head>
        <meta
          name="description"
          content="Check out all the projects I have done."
        />

        <meta property="og:title" content="Projects | Ifeanyi Umeh" />

        <meta
          property="og:description"
          content="Check out all the projects I have done."
        />

        <meta property="og:type" content="website" />

        <meta
          property="og:image"
          content="https://ifeanyiumeh.com/src/Profile_pix.png"
        />

        <meta property="og:url" content="https://ifeanyiumeh.com" />
        <title>Where to buy - Royal Electronics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-sm.svg" />
        <link rel="apple-touch-icon" href="/favicon-md.svg" />
      </Head>

      <div className="w-full flex justify-center h-screen items-center mt-[100px]">
        <p className="text-bold text-5xl text-black">StoreLocator page</p>
      </div>
    </div>
  );
};

export default StoreLocator;
