import React from "react";
import Head from "next/head";
import HeroSection from "../../../components/ProductPage/HeroSection";
import LinkTree from "../../../components/ProductPage/LinkTree";
import RecommendedSection from "../../../components/ProductPage/RecommendedSection";
import { products } from "../../../productsAPI";

const Product = ({ projects }) => {
  return (
    <div className="">
      <Head>
        <meta
          name="description"
          content="Check out all the projects I have done."
        />

        <meta property="og:title" content="Projects | Ifeanyi Umeh" />

        <meta
          property="og:description"
          content="Check out all the projects I have done."
        />

        <meta property="og:type" content="website" />

        <meta
          property="og:image"
          content="https://ifeanyiumeh.com/src/Profile_pix.png"
        />

        <meta property="og:url" content="https://ifeanyiumeh.com" />
        <title>Royal Electronics - Affordable luxury</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-sm.svg" />
        <link rel="apple-touch-icon" href="/favicon-md.svg" />
      </Head>

      <LinkTree />
      <HeroSection
        img={projects.img}
        img2={projects.img2}
        img3={projects.img3}
        title={projects.title}
        desc={projects.desc}
      />
      <RecommendedSection rowID="1" />
    </div>
  );
};

export default Product;

export const getStaticProps = async ({ params }) => {
  const data = products.filter((p) => p.slug === params.slug);

  return {
    props: {
      projects: data[0],
    },
  };
};

export const getStaticPaths = async () => {
  const paths = products.map((projects) => ({
    params: { slug: projects.slug },
  }));
  return { paths, fallback: false };
};
